#!/bin/sh
#
# kubetail - Kubernetes log tail script
#
# Author: Jonathan Cormier <jonathan@cormier.co>
#
# Example:
#
# $ kubetail my-pod
# ...
# <output from my-pod>
# ...
# $
#

# Script options
TIMESTAMPS=0
PREFIX=1
ALL=0

# Path to kubectl
KUBECTL=$(which kubectl)
CONTAINER=$2

# Parse command line or print usage
if [ $# -ge 1 ]; then
	SEL=$1
else
	echo "Usage: $0 [POD|SELECTOR|DEPLOYMENT] [CONTAINER]"
	echo
	echo "POD - pod [example]"
	echo "SELECTOR - selector for pod selection [label=example]"
	echo "DEPLOYMENT - deployment [deployment/example]"
	echo
	echo "CONTAINER - limit output to CONTAINER" 

	exit
fi

# Basic command to query logs
KUBECMD="$KUBECTL logs --follow"

# Timestamps
[ $TIMESTAMPS -eq 1 ] && KUBECMD="$KUBECMD --timestamps"

# Prefix
[ $PREFIX -eq 1 ] && KUBECMD="$KUBECMD --prefix"

# All containers
[ $ALL -eq 1 ] && KUBECMD="$KUBECMD --all-containers"

# Check for selector
case $SEL in 
	*"="*)
		# Found selector
		KUBECMD="$KUBECMD -l $SEL"
		;;
	*)
		# Default use pods/deployments
		KUBECMD="$KUBECMD -p $SEL"
esac

# Add container to command
[ ! -z $CONTAINER ] && KUBECMD="$KUBECMD -c $CONTAINER"

# Run KUBECMD 
eval $KUBECMD
